#
# Copyright (c) 2019 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  labels:
    app: portal
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:713452077550:certificate/4a59f14c-0925-4a41-abaf-32a1de900db1"
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
   service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
   service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  ports:
    - port: 443
      name: https
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: portal